### PR TITLE
Start of port to new Zenodo API

### PR DESCRIPTION
**Pull request by alexlancaster**
Applying against 0.10.0 to match the action.

First commit switches content-type to`application/octet-stream` for uploads

### CODE REVIEW

**Comment by alexlancaster** [comment]
This supercedes the old PR #77  and is attempt to fix https://github.com/zenodraft/action/issues/25

@jspaaks I was able to update my own local version of the action and it fixed the upload, see: 

https://github.com/alexlancaster/pypop/actions/runs/6541502439/job/17763112921#step:6:479

Unfortunately the metadata update still fails (looking at that next):

https://github.com/alexlancaster/pypop/actions/runs/6541502439/job/17763112921#step:6:513

It could be as simple as updating the content-type to `application/octet-stream` as well.

**Comment by alexlancaster** [comment]
> Unfortunately the metadata update still fails (looking at that next):
> 
> https://github.com/alexlancaster/pypop/actions/runs/6541502439/job/17763112921#step:6:513
> 
> It could be as simple as updating the content-type to `application/octet-stream` as well.

Turns out that `500` error was due to an error in my `.zenodo.json` file, now that I've fixed it, it finally works!

https://github.com/alexlancaster/pypop/actions/runs/6542518454/job/17765670793

Apparently it doesn't like the the 

```
"license": {
  "id": "GPL-2.0-or-later"
}
```

-style JSON anymore.  But I can't seem to otherwise set the license - it keeps defaulting back to Creative Commons.

**Comment by alexlancaster** [comment]
Upload of new version not yet working:

https://github.com/alexlancaster/pypop/actions/runs/6542595070/job/17765853318#step:6:197

```
 creating a new, empty versioned deposition in existing collection...
  checking that the collection_id value resolves to a concept, not a version...
  getting id of the latest version in the collection...
  Error: Cannot read properties of undefined (reading 'split')
```

**Comment by alexlancaster** [comment]
> Upload of new version not yet working:
> 
> https://github.com/alexlancaster/pypop/actions/runs/6542595070/job/17765853318#step:6:197
> 
> ```
>  creating a new, empty versioned deposition in existing collection...
>   checking that the collection_id value resolves to a concept, not a version...
>   getting id of the latest version in the collection...
>   Error: Cannot read properties of undefined (reading 'split')
> ```

I think this is because I'm trying to use a collection that is still in "draft" mode.  Apparently I can't add a new version to an unpublished collection.  Since I'm testing this on the main zenodo.org instance, I obviously don't want to publish the initial deposition.  

Unfortunately, the sandbox.zenodo.org still seems to be broken (by the API and via the web GUI).  You can create empty draft depositions, and upload files to them, but can't update metadata, nor delete drafts.  So back to waiting for upstream to fix sandbox.

**Comment by alexlancaster** [comment]
OK, so something has changed again on the Zenodo side, now it is failing with a different  error: `403 - FORBIDDEN` (the API key is working because I am able to update metadata).

```
 adding file pypop.zip to deposition with id 10027957...
  Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: {
      body: PassThrough {
        _readableState: [ReadableState],
        _events: [Object: null prototype],
        _eventsCount: 2,
        _maxListeners: undefined,
        _writableState: [WritableState],
        allowHalfOpen: true,
        [Symbol(kCapture)]: false,
        [Symbol(kCallback)]: null
      },
      disturbed: false,
      error: null
    },
    [Symbol(Response internals)]: {
      url: 'https://zenodo.org/api/files/3fb20070-5bc7-40d9-9f33-4539a5fec8b9/pypop.zip',
      status: 403,
      statusText: 'FORBIDDEN',
      headers: Headers { [Symbol(map)]: [Object: null prototype] },
      counter: 0
    }
  }
  Error: Something went wrong on PUT to https://zenodo.org/api/files/3fb20070-5bc7-40d9-9f33-4539a5fec8b9/pypop.zip: 403 - FORBIDDEN 
```
See full log here:

https://github.com/alexlancaster/pypop/actions/runs/6590602449/job/17907554271#step:6:510

I have reported to Zenodo tech support upstream as a new ticket.

**Comment by alexlancaster** [comment]
@jspaaks 

I even tried to upload files outside `zenodraft` completely using the documented API here: https://developers.zenodo.org/?shell#quickstart-upload using curl:

```
 curl --upload-file pypop-guide.pdf https://zenodo.org/api/files/3fb20070-5bc7-40d9-9f33-4539a5fec8b9/pypop-guide.pdf?access_token=$ZENODO_ACCESS_TOKEN 
```
and I get the same problem:
```
{"status": 403, "message": "Permission denied."}
```

So it's clearly an API issue.  This is despite the fact that metadata upload works.

**Comment by alexlancaster** [comment]
> @jspaaks
> 
> I even tried to upload files outside `zenodraft` completely using the documented API here: https://developers.zenodo.org/?shell#quickstart-upload using curl:
> 
> ```
>  curl --upload-file pypop-guide.pdf https://zenodo.org/api/files/3fb20070-5bc7-40d9-9f33-4539a5fec8b9/pypop-guide.pdf?access_token=$ZENODO_ACCESS_TOKEN 
> ```
> 
> and I get the same problem:
> 
> ```
> {"status": 403, "message": "Permission denied."}
> ```
> 
> So it's clearly an API issue. This is despite the fact that metadata upload works.

OK, I started to be able to upload again, but it was hit and miss until just now. And one successful upload to Zenodo via the `zenodraft` action:

https://github.com/alexlancaster/pypop/actions/runs/6634689733/job/18024493872

so it seems that it's not an API incompatibility issue, but a performance/robustness issue with the server being able to accept uploads. I hope it's stable enough now to be reliable.

**Comment by alexlancaster** [comment]
@jspaaks uploads are reliable again, and I've now managed to actual publish the PyPop 1.0.0 release using the action:

https://zenodo.org/records/10080668

and you're listed as an author.

Now that there's a published release, I tried going back and adding the collection ID back to the action so that subsequent releases are new versions, i.e.

```
 collection: 10080667
```

Unfortunately there may be an API change related to new versions that requires a deeper change:

```
 creating a new, empty versioned deposition in existing collection...
  checking that the collection_id value resolves to a concept, not a version...
  getting id of the latest version in the collection...
  creating a new version off of latest version in collection...
  Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: {
      body: PassThrough {
        _readableState: [ReadableState],
        _events: [Object: null prototype],
        _eventsCount: 5,
        _maxListeners: undefined,
        _writableState: [WritableState],
        allowHalfOpen: true,
        [Symbol(kCapture)]: false,
        [Symbol(kCallback)]: null
      },
      disturbed: false,
      error: null
    },
    [Symbol(Response internals)]: {
      url: 'https://zenodo.org/api/deposit/depositions/latest/actions/newversion',
      status: 404,
      statusText: 'NOT FOUND',
      headers: Headers { [Symbol(map)]: [Object: null prototype] },
      counter: 0
    }
  }
  Error: Something went wrong on POST to https://zenodo.org/api/deposit/depositions/latest/actions/newversion: 404 - NOT FOUND 
  ```

see the build log here: https://github.com/alexlancaster/pypop/actions/runs/6791011469/job/18461656177#step:6:197

I think creating new depositions works slightly differently now.  This is the first time I've been able to test this part - with sandbox being down - I had to wait until I had a published version to be able to update. 

I'll try and take a look, but any insights would be useful.  As I can't add new releases to the record without this working.

**Comment by alexlancaster** [comment]
My hunch is that it's related to this change: https://help.zenodo.org/docs/about/whats-changed/#deposit-versioning  apparently when a new version created, it doesn't automatically copy over the old files. 

I have managed to partially create a new version using the command-line interface:

```
npx zenodraft -v deposition create in-existing-collection 10080667
creating a new, empty versioned deposition in existing collection...
checking that the collection_id value resolves to a concept, not a version...
getting id of the latest version in the collection...
deposition links: {"self":"https://zenodo.org/api/records/10080668","html":"https://zenodo.org/records/10080668","doi":"https://doi.org/10.5281/zenodo.10080668","parent_doi":"https://zenodo.org/doi/10.5281/zenodo.10080667","badge":"https://zenodo.org/badge/doi/10.5281%2Fzenodo.10080668.svg","conceptbadge":"https://zenodo.org/badge/doi/10.5281%2Fzenodo.10080667.svg","files":"https://zenodo.org/api/records/10080668/files","bucket":"https://zenodo.org/api/files/cc50542f-1750-4eca-95b3-34d1cc639b0b","latest_draft":"https://zenodo.org/api/deposit/depositions/10080668","latest_draft_html":"https://zenodo.org/deposit/10080668","publish":"https://zenodo.org/api/deposit/depositions/10080668/actions/publish","edit":"https://zenodo.org/api/deposit/depositions/10080668/actions/edit","discard":"https://zenodo.org/api/deposit/depositions/10080668/actions/discard","newversion":"https://zenodo.org/api/deposit/depositions/10080668/actions/newversion","registerconceptdoi":"https://zenodo.org/api/deposit/depositions/10080668/actions/registerconceptdoi","record":"https://zenodo.org/api/records/10080668","record_html":"https://zenodo.org/record/10080668","latest":"https://zenodo.org/api/records/10080668/versions/latest","latest_html":"https://zenodo.org/record/10080668/versions/latest"}
deposition link latest: "https://zenodo.org/api/deposit/depositions/10080668"
creating a new version off of latest version in collection...
created new record 10080974
10080974
removing any files from the newly drafted version...
removing pypop.zip from version 10080974 ...
clearing metadata from deposition with id 10080974...
Updated record 10080974.
Response {
  size: 0,
  timeout: 0,
  [Symbol(Body internals)]: {
    body: PassThrough {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: true,
      [Symbol(kCapture)]: false,
      [Symbol(kTransformState)]: [Object]
    },
    disturbed: false,
    error: null
  },
  [Symbol(Response internals)]: {
    url: 'https://zenodo.org/api/files/66001ee6-af63-44a5-ba0f-95c93e6e112c/pypop.zip',
    status: 500,
    statusText: 'INTERNAL SERVER ERROR',
    headers: Headers { [Symbol(map)]: [Object: null prototype] },
    counter: 0
  }
}
(node:372792) UnhandledPromiseRejectionWarning: Error: Something went wrong on PUT to https://zenodo.org/api/files/66001ee6-af63-44a5-ba0f-95c93e6e112c/pypop.zip: 500 - INTERNAL SERVER ERROR 
    at /tmp/zenodo/node_modules/zenodraft/dist/file/delete.js:37:15
    at Generator.next (<anonymous>)
    at fulfilled (/tmp/zenodo/node_modules/zenodraft/dist/file/delete.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:372792) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:372792) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

basically the failure happens upon attempted deletion of the files.  If I remove that line, it works (but the original zip file still remains on the Zenodo side).

**Comment by alexlancaster** [comment]
Also looking at https://developers.zenodo.org/?shell#delete28  it seems the example API gives a different URL structure  for deletion, e.g.:

```
curl -i -X DELETE https://zenodo.org/api/deposit/depositions/1234/files/21fedcba-9876-5432-1fed-cba987654321?access_token=ACCESS_TOKEN
```
Has this changed since you implemented it?

**Comment by alexlancaster** [comment]
Thought that this might be fixed upstream eventually, but still no luck.  From https://github.com/alexlancaster/pypop/actions/runs/6937421905/job/18871445555 

```
creating a new, empty versioned deposition in existing collection...
  checking that the collection_id value resolves to a concept, not a version...
  getting id of the latest version in the collection...
  creating a new version off of latest version in collection...
  Response {
    size: 0,
    timeout: 0,
    [Symbol(Body internals)]: {
      body: PassThrough {
        _readableState: [ReadableState],
        _events: [Object: null prototype],
        _eventsCount: 2,
        _maxListeners: undefined,
        _writableState: [WritableState],
        allowHalfOpen: true,
        [Symbol(kCapture)]: false,
        [Symbol(kCallback)]: null
      },
      disturbed: false,
      error: null
    },
    [Symbol(Response internals)]: {
      url: 'https://zenodo.org/api/deposit/depositions/latest/actions/newversion',
      status: 404,
      statusText: 'NOT FOUND',
      headers: Headers { [Symbol(map)]: [Object: null prototype] },
      counter: 0
    }
  }
  Error: Something went wrong on POST to https://zenodo.org/api/deposit/depositions/latest/actions/newversion: 404 - NOT FOUND 
```

@jspaaks have you had a chance to check out the new Zenodo?

**Comment by alexlancaster** [comment]
> This PR is now superseded by PR #79. Thanks Alex for making this, it helped jumpstart things. 

Great - this is good to see!

> I added you as a contributor with affiliation `amberbiology.com` from you profile, let me know if that's ok

That's fine with me. You're also listed in the acknowledgments of the PyPop paper we just submitted to a journal. I'm happy to test the new version as well.

Also will there be an update of the corresponding @zenodraft action? I'd like to be able to deploy end to end. Right now I've been using my own modified version, but I'd like to switch back to upstream as soon as possible.

**Comment by jspaaks** [comment]
Hi @alexlancaster ,
I released `zenodraft` 0.13.3 on NPM and GitHub Marketplace, I'd be interested to know if they work for you. 

Note: the action used to have a property called `collection` which has been renamed to `concept` for consistency with Zenodo terminology.

**Comment by alexlancaster** [comment]
> Hi @alexlancaster ,
> I released `zenodraft` 0.13.3 on NPM and GitHub Marketplace, I'd be interested to know if they work for you. 
> 
> Note: the action used to have a property called `collection` which has been renamed to `concept` for consistency with Zenodo terminology.
> 

Awesome @jspaaks !

Happy to give it a test on the pypop repo in branch. I'll keep you posted.

**Comment by alexlancaster** [comment]
> > Hi @alexlancaster ,
> > I released `zenodraft` 0.13.3 on NPM and GitHub Marketplace, I'd be interested to know if they work for you.
> > Note: the action used to have a property called `collection` which has been renamed to `concept` for consistency with Zenodo terminology.
> 
> Awesome @jspaaks !
> 
> Happy to give it a test on the pypop repo in branch. I'll keep you posted.

Looks like it works out of the box - nice!  The downstream packages are still building but here's the Zenodo part:

https://github.com/alexlancaster/pypop/actions/runs/7795044827/job/21257398597

here's the changed section in the action:

https://github.com/alexlancaster/pypop/blob/6e4d16e3f293485030ef1fe2bc5b3d4caea86a86/.github/workflows/build_wheels.yml#L99-L118

Looks like I can now retire my branch!

**Comment by jspaaks** [comment]
> Looks like it works out of the box - nice!

Woohoo that's what I like to see :tada:

**Pull request closed without merging**
